import './globals.css'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './registry.styled-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Comercia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-pt">
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
